### ISSUE TITLE
Enable search on rule id

### ISSUE THREAD

**Issue by Paul-Blanchaert** [querqy/smui#101]
Currently, the toggle 'toggle.rule-deployment.log-rule-id' allows to export the rule id in the querqy rule _log property towards Solr.
In Solr, we can see that log entry (with the id) of applied rule in the querqy.infoLogging tag.
However, a SMUI user has no option to look for the rule in SMUI based on the rule id of the querqy infoLogging.
Could we enable the lookup of the rule via the rule id in the SMUI rule filter (similar to the filter on an inputTag)?

**Comment by pbartusch** [comment]
Hi @Paul-Blanchaert ,

it should be very easy to implement a festure that allows lookup for a rule id in the input field (using the instant search).

Just to make you aware: Depending on the use case, there has been a lot of discussion on logging the rule id. E.g. for analytical insights the tracked rule id can be used to re-identify the rule using the whole DB. Also there was the idea to create a shortened or even readable identifier, e.g. 'cheap-notebook', instead of the rule id for querqy's log.

Let me know, if I can help you further on the specific use case.

Cheers,
Paul :-)

**Comment by Paul-Blanchaert** [comment]
Hi @pbartusch 
Finally found some time to implement this change.
See PR Enable lookup of rule by id #107

**Comment by renekrie** [comment]
Implemented by #107
