### ISSUE TITLE
Internal Server Error when generating report

### ISSUE THREAD

**Issue by omgMath** [querqy/smui#114]
Hi

We receive an Internal Server Error when trying to generate a report:
The request is sent to `/api/v1/report/activity-report/foo?dateFrom=2020-06-25&dateTo=2022-06-15`.

The server logs show the following:
```
play.api.UnexpectedException: Unexpected exception[NoSuchElementException: head of empty list]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:347)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:448)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:446)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Caused by: java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:430)
	at scala.collection.immutable.Nil$.head(List.scala:427)
	at models.eventhistory.InputEvent$.isEventForSolrIndex$1(InputEvent.scala:311)
	at models.eventhistory.InputEvent$.$anonfun$allChangedInputIdsForSolrIndexIdInPeriod$1(InputEvent.scala:317)
	at models.eventhistory.InputEvent$.$anonfun$allChangedInputIdsForSolrIndexIdInPeriod$1$adapted(InputEvent.scala:317)
	at scala.collection.TraversableLike.allIn$1(TraversableLike.scala:320)
	at scala.collection.TraversableLike.noneIn$1(TraversableLike.scala:307)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:372)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:284)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
```

If I select a shorter time window, e.g. `/api/v1/report/activity-report/brackDE?dateFrom=2022-06-01&dateTo=2022-06-15`, the request works, but returns
```json
{
    "items": []
}
```
We're using SMUI version v3.13.1. Are we missing some configuration? Couldn't find anything on reports in the docs.

Thanks for looking into that.

**Comment by dobestler** [comment]
I have the same issue and I can't see Latest rule management activities for certain periods.
IMO there are cases where the current concept of the event history does not cover that lead to this and other exceptions. In short: 
Event History feature can be turned on (`toggle.activate-eventhistory`), then a data migration "pre_v3.8" runs and creates virtual "CREATED" because the App is counting on it. Problem: Event History can be turned off again and all the rule management activities are not recorded. If you turn it on again, the migration "pre_v3.8" is not run again which leads to inconsistent states of events (because the virtual CREATED are missing for all new rules created in between).

There is also a very simple and probably common use case where  `NoSuchElementException: head of empty list` happens
Reproduce it by the following steps:
1. Start SMUI with toggle.activate-eventhistory=false
2. Create one first Search Input together with e.g. a Synonym Rule
3. Generate the "Latest rule management activities" Report

If you start SMUI with `toggle.activate-eventhistory=true` there is a migration running that create "virtual create events" which might fix the problem.

Still, if you delete a Rule that was created before `toggle.activate-eventhistory=true`, there seems to pop up another problem when showing the Activity Log on the Rule Detail View:

`[error] m.e.ActivityLog - IllegalState: processInputEvents found event chain (None, UPDATED)
[error] m.e.ActivityLog - beforeEvent = >>>None
[error] m.e.ActivityLog - afterEvent = >>>InputEvent(d5b85226-8070-4959-bdfc-cdaa9d713dbe,SearchInput,1,2024-04-16T18:52:25,None,b82d7685-abfc-4213-ab5a-7304e18164aa,Some({"id":"b82d7685-abfc-4213-ab5a-7304e18164aa","term":"history-off-2","synonymRules":[{"id":"1d4b3387-0c6b-42cc-a108-881c1a591bda","synonymType":0,"term":"create_syn2_hist_off -> update_hist_on","isActive":true}],"upDownRules":[],"filterRules":[],"deleteRules":[],"redirectRules":[],"tags":[],"isActive":true,"comment":"","solrIndexId":"fe1e55d9-4a35-4f53-8dec-b26e32a77e68","lastUpdate":"2024-04-16T18:52:25"}))
`


the expected state changes are noted in ActivityLog.scala (L385)

    // support the following valid event constellations:
    // before -> after    | compare activity
    // ~~~~~~~~~~~~~~~~~~ | ~~~~~~~~~~~~~~~~
    // None    -> CREATED | event, output all contents of beforeEvent as after, before = empty
    // CREATED -> DELETED | events, output all contents of beforeEvent as before, after = empty
    // CREATED -> UPDATED | events, output diff of before/after
    // UPDATED -> UPDATED | events, output diff of before/after
    // UPDATED -> DELETED | events, output all contents of beforeEvent as before, after = empty
    // (important: CREATED and VIRTUALLY_CREATED are equal in that context)


**What can we do?**
1. Fix the conceptual issues that can happen when Event History feature is turned on and off and on again. E.g. by always recording events and not only if the feature is turned on. BUT this needs to be done together with a one time migration of inconsistent data as well.
2. Patch the application so it can deal better with inconsistent states that we currently have and leave everything else as is (and maybe fix the conceptual problems later). The easy way to allow for more valid event constellations in ActivityLog.scala like 
    Fix 1:

    // **None    -> UPDATED** | events, before = empty, after = all contents of afterEvent
    // **None    -> DELETED** | events, before = empty, after = empty

    Fix 2:
    And fix the `NoSuchElementException: head of empty list` by simply skipping this case. It happens if there is a DELETED event without preceding CREATED event.

**Suggestion: Patch the application** see #152

**Comment by mkr** [comment]
We can live with the patch for now. My preferred solution would be to remove the toggle altogether and always create the activity log.

**Comment by mkr** [comment]
Ah, and thanks @dobestler :)

**Comment by epugh** [comment]
> We can live with the patch for now. My preferred solution would be to remove the toggle altogether and always create the activity log.

I love the toggles for new things, as a feature flag, but would love to see things that work well become default on!
