### ISSUE TITLE
SMUI tags managing

### ISSUE THREAD

**Issue by raniadhahbi** [querqy/smui#154]
Hello, I'm currently working on the tags in SMUI and I need to add new tags and manage them via the UI but cannot find any key to activate this option neither i found the components to do it.
So, did anyone managed to do this ? Thank you !

**Comment by mkr** [comment]
Hi @raniadhahbi, tags can be used if you want to distinguish between certain sets of rules. There are no predefined tags, you would need to specify tags yourself based on your use case.

Example:
* You manage rules for two sites but don't want to split them into two rules collections in SMUI because some rules should apply for both sites while some are specific for only one of the two sites.
* You could create a tag definition file tags.json that looks like this
```
[
  {
    "property": "tenant",
    "value": "site1only"
  },
  {
    "property": "tenant",
    "value": "site2only"
  }
]
```
* You then instruct SMUI to start with tags support, e.g. `docker run -e SMUI_DB_JDBC_DRIVER=org.sqlite.JDBC -e SMUI_DB_URL=jdbc:sqlite:/tmp/tmp.db -e SMUI_RULE_TAGGING_ACTIVE=true -v ./tags.json:/tags.json -e SMUI_PREDEFINED_TAGS_FILE=/tags.json -p 9000:9000 --rm querqy/smui:4.1.1`
* This starts a SMUI docker container, mounts the tags.json into the root folder, enables the tagging UI features by setting `SMUI_RULE_TAGGING_ACTIVE=true` and configures the tags file with `SMUI_PREDEFINED_TAGS_FILE=/tags.json`.
* You will then have a drop-down next to each input to optionally pick a tag value.

**Comment by raniadhahbi** [comment]
Hi @mkr well i did manage to add them and now I have the toggle of the tags but now I need to create a new tag from the UI directly without basing on the json file, And I cound't find how to active it ,Have any idea please?

**Comment by mkr** [comment]
Hi @raniadhahbi I think this feature has not been implemented yet and so far SMUI only supports supplying a tag list file which is synced into the SMUI DB upon startup.

**Comment by raniadhahbi** [comment]
Hi @mkr ah okay so this option doesn't exist in SMUI, thank you so much for your rapid responsiveness and your help !

**Comment by mkr** [comment]
Thanks @raniadhahbi, I hope SMUI is still helpful for you, I'm closing this issue for now.

**Comment by raniadhahbi** [comment]
yes it is thank you @mkr. you can close it
