### ISSUE TITLE
Rule validation (on save) - frontend communication (to search manager)

### ISSUE THREAD

**Issue by pbartusch** [querqy/smui#23]
When saving a rule a server-side validation is triggered. Unfortunately, the results of this validation is only logged (server-side) and never communicated to the user. So, this issue is about:

 - marking invalid rules when (a) loading the rules after selection of an search input or (b) saving edited rules
 - invalid rules should be marked live- / rule-wise
 - saving edited search input with invalid rules should also return an error Toast message (red). update persistence should not be done.

Validation should contain:
 - resulting querqy-rules.txt in total is parseable by querqy
 - invalid undirected synonyms (using * and $n)
 - invalid target URLs for REDIRECT rules
 - empty rule input / parameters (synonym, UP/DOWN term, etc.)
 - etc.

**Comment by schnoddelbotz** [comment]
One more proposal for validation that would be helpful: UP/DOWN rules with multiple terms need to quoted, as they lead to Solr exceptions otherwise (see Screenshot for correct(ed) usage example). If quoting is omitted, it will lead to `Error from server at http.../solr/collection: no field name specified in query and no default specified via 'df' param at ...`.
<img width="2338" alt="Screenshot 2019-11-25 at 10 17 09" src="https://user-images.githubusercontent.com/2153919/69527716-2849d280-0f6d-11ea-9e3b-c18b3303282c.png">

**Comment by renekrie** [comment]
Heads up: Using quotes really means a phrase. The user might just want so say: I want both terms in that field, which could also be expressed using `field:(term1 term2)`. So, maybe the validation should consider both options.

On that note, there is some work in Querqy to allow for phrases also on the right-hand side of queries that don't use Solr/Lucene syntax: https://github.com/renekrie/querqy/issues/67

**Comment by pbartusch** [comment]
invalid rules get communicated to the search manager, so this issue is mainly closed. new validation issues should result in new issues.
