### ISSUE TITLE
Admin Screen to manage Suggested Solr fields

### ISSUE THREAD

**Issue by epugh** [querqy/smui#65]
I don't yet have practical experience on how much we'll use the suggested Solre fields feature.  However, if we do start using them, it would be nice to be able to have an admin interface to pick them.   Over in Quepid land, we actually query the underlying search engine (Solr, Elasticsearch) to get a list of fields, and then have a filtering picker to let the user pick the one.

Otherwise we are doing:
```
curl -S -X PUT -H "Content-Type: application/json" -d '{"name":"product_type"}' http://localhost:9000/api/v1/${SOLR_INDEX_ID}/suggested-solr-field
```

**Comment by renekrie** [comment]
As far as I can see, the majority of UP/DOWN/FILTER rules uses fields. However, so far we could avoid coupling SMUI with Solr. Maybe, that's again more like a script, which provides the fields and which could be adjusted to the different Solr access scenarios (like the rule deployment).

Also, opening up a field for use in search management should indeed have very restricted access in order to keep up control - we'd definitely need an admin role for it.

**Comment by mkr** [comment]
Tight coupling has its advantages as we would allow for much more functionality around immediate feedback/preview (things like typos in filter expressions that lead to syntactic errors, see immediately how many documents does an expression capture etc.). On the other hand, I could imagine a fixed list of fields that one *needs* to pick from can be more helpful than suggesting the potentially hundreds of (dynamic) fields.

**Comment by renekrie** [comment]
Yes, I can see that. Maybe just having an abstraction `SearchEngine` solves the problem.

**Comment by pbartusch** [comment]
I agree:

* with @epugh : Field names for the search engine (like Solr) should be suggested from the search engine itself.
* with @mkr : That there is potential to improve SMUI while coupling SMUI with the search engine. But: This coupling should be very loose and only optional - which should work for the suggested fields.

So I see 2 contact points, where SMUI uses the specific search engine:

1.  Supporting the Search Manager: should be optional, e.g. when suggesting (Solr) fields, validation, maybe a preview in the future
2. Exporting the `rules.txt` file and deploy it to the search engine

As for the latter, I see #56 connected to this issue.

**Comment by renekrie** [comment]
On this note, I still think that using templates (https://github.com/querqy/smui/issues/56#issuecomment-748524907) could be a great solution here. Not exactly a field list, but something that uses fields and that could provide us with search-engine specific query syntax. We could give the admin user the powers to manage templates (for whatever complexity of the query) and generate the UI from parameter documentation.

**Comment by dobestler** [comment]
I see the point of the abstraction with suggested fields as it greatly simplifies the majority of use cases, I assume. Do you think it might be useful to have the ability to define a raw query to a rule as well? E.g. as a specific option instead of choosing from suggested fields. The advantage would be to enable basically all use cases for rules through SMUI. It could be useful as a rather inconvenient way to enabling Elastic dialect in the rules because it's delegated to the user. It could enable Elastic Rules completely as a first step and circumvent the templates discussion and similar approaches.
Tradeoff being the higher risk of human error when writing raw query syntax unless there is validation added to these inputs.
